language: node_js
node_js:
  - 10.16.3

before_install:
  - openssl aes-256-cbc -K $encrypted_f3b1037fc47f_key -iv $encrypted_f3b1037fc47f_iv -in quanht.pem.enc -out quanht.pem -d
  - chmod 700 quanht.pem

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - ssh -i quanht.pem -o StrictHostKeyChecking=no ubuntu@18.162.151.91 'bash -s' < deploy.sh $nodeHome
    on:
      branch: master
branches:
  only:
    - master

