language: node_js
node_js:
  - 10.16.3

before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out quanht.pem -d
  - chmod 700 quanht.pem

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - rsync -delete -e "ssh -i quanht.pem -o StrictHostKeyChecking=no" ./ quanht@34.87.80.48:/home/quanht/Campathon2019
      - ssh -i quanht.pem -o StrictHostKeyChecking=no quanht@34.87.80.48 'bash -s' < deploy.sh $nodeHome Campathon2019
    on:
      branch: master
branches:
  only:
    - master

